### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by GodKra** [wsendon/quartz#2]
add Metadata to CSpawnMob.go packet
add NBTData to CUpdateBlockEntity.go packet
add JSONData to CChatMessage.go packet
add WindowTitle to COpenWindow.go packet
add SlotData to CSetSlot.go packet
add Metadata to CSpawnPlayer.go packet
add SlotData to CWindowItems.go packet

**Comment by GodKra** [comment]
Also check string length while constructing the packet.

**Comment by wsendon** [comment]
Check difficulty range in CServerDifficulty.

**Comment by wsendon** [comment]
Add packet constructors for packets with String(n)
